"""Build CurbCall's databases from data/ and the shared GeoAI Cities DB.

Outputs
  db/curbcall.sqlite  ready-to-query SQLite copy (no server, no extensions)
  db/seed.sql         INSERT statements for the PostGIS schema in db/schema.sql

Neighborhoods and areas come from geoai-cities-db (set GEOAI_DB, or keep the two
repositories side by side).

    python scripts/build_db.py
"""
import json
import os
import sqlite3
import sys
from pathlib import Path

import geopandas as gpd

ROOT = Path(__file__).resolve().parents[1]
D, DB = ROOT / "data", ROOT / "db"
sys.path.insert(0, str(Path(os.environ.get("GEOAI_DB_REPO", ROOT.parent / "geoai-cities-db"))))
from geoai_db import read  # noqa: E402


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    hoods = read("sd_neighborhoods")
    checks = json.loads((D / "checklists.json").read_text())
    reports = gpd.read_file(D / "example_reports.geojson")
    reports = gpd.sjoin(reports, hoods[["name", "area_name", "geometry"]], how="left", predicate="within")
    assert reports.name.notna().all(), "every report must fall inside a neighborhood"
    votes = []  # resident votes are never committed; the prototype's only vote is a test

    # ---------- SQLite ----------
    DB.mkdir(exist_ok=True)
    path = DB / "curbcall.sqlite"
    path.unlink(missing_ok=True)
    con = sqlite3.connect(path)
    con.executescript((ROOT / "db" / "sqlite_schema.sql").read_text())
    con.executemany("INSERT INTO neighborhoods VALUES (?,?,?)",
                    [(int(r.neighborhood_id), r["name"], r.area_name) for _, r in hoods.iterrows()])
    con.executemany("INSERT INTO report_types VALUES (?)", [(t,) for t in checks["types"]])
    cond = [(t, c) for t, cs in checks["types"].items() for c in cs] + [(None, c) for c in checks["common"]]
    con.executemany("INSERT INTO conditions (type_name, label) VALUES (?,?)", cond)
    for _, r in reports.iterrows():
        con.execute("INSERT INTO reports VALUES (?,?,?,?,?,?,?,?,?,?,?)",
                    (r.report_id, r.title, r["type"], r.where_text, r.details, r.geometry.x, r.geometry.y,
                     r["name"], r.area_name, 1, None))
        for label in filter(None, (r.checklist or "").split("|")):
            cid = con.execute("SELECT id FROM conditions WHERE label = ? AND (type_name = ? OR type_name IS NULL)",
                              (label, r["type"])).fetchone()
            if cid:
                con.execute("INSERT INTO report_conditions VALUES (?,?)", (r.report_id, cid[0]))
    con.commit()

    # ---------- PostGIS seed ----------
    out = ["-- Generated by scripts/build_db.py. Run after db/schema.sql.", "BEGIN;"]
    out += [f"INSERT INTO report_types VALUES ({q(t)}) ON CONFLICT DO NOTHING;" for t in checks["types"]]
    out += [f"INSERT INTO conditions (type_name, label) VALUES ({q(t)}, {q(c)}) ON CONFLICT DO NOTHING;"
            for t, c in cond]
    for _, r in reports.iterrows():
        out.append("INSERT INTO reports (report_id, title, type_name, where_text, details, geom, is_example) "
                   f"VALUES ({q(r.report_id)}, {q(r.title)}, {q(r['type'])}, {q(r.where_text)}, {q(r.details)}, "
                   f"ST_SetSRID(ST_MakePoint({r.geometry.x}, {r.geometry.y}), 4326), TRUE) ON CONFLICT DO NOTHING;")
    out.append("COMMIT;")
    (DB / "seed.sql").write_text("\n".join(out) + "\n")
    print(f"{len(hoods)} neighborhoods, {len(reports)} example reports, {len(votes)} votes -> db/")


if __name__ == "__main__":
    main()
